services:
  - type: web
    name: clima-rio-tercero-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python clima_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 